CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE SCHEMA IF NOT EXISTS quartz;
CREATE ROLE law_it_admin WITH ENCRYPTED PASSWORD 'pass';
ALTER DATABASE law_it OWNER TO law_it_admin;
ALTER ROLE law_it_admin WITH LOGIN;
